addons/dialogue_manager/dialogue_label.gd
If you have dialogue that has responses immediately after a mutation:
```
~ test
Welcome!
set has_been_welcomed = true
- hi
- bye
```
Or if the dialogue _begins_ with responses:
```
~ test
- hi
- bye
```
You'll get a `Division By Zero in operator '/'.` error:
This PR fixes that by returning from `type_out()` early if `get_total_character_count()` is `0`.
=> Prevent `Division By Zero in operator '/'.` error when responses don't come immediately after a dialogue line

addons/dialogue_manager/components/parser.gd
This fixes an issue where the `extract_markers` function in `parser.gd` sometimes places BBCode tags in the wrong location due to not correctly interpreting the locations of the other codes (wait, speed, etc.).
Here is what the following line looks like in the test scene before and after this change.
`Test: Waiting for [b]boldness[/b]...[wait=3] Waiting for [i]italics[/i]...[wait=4] Done [color=blue]blue[/color] waiting! `
Before fix:
After fix:
=> Fix parsing multiple types of codes

.gitattributes
Small issue I noticed while downloading the project from the asset lib.
This changes will make the godot downloader only add the `/addons` folder by default (users can still add docs and other folders from the dialogue)
Recommended in the [godot docs](https://docs.godotengine.org/en/stable/community/asset_library/submitting_to_assetlib.html)
=> Add asset-lib gitattribute recommendations

addons/dialogue_manager/dialogue_manager.gd, docs/Using_Dialogue.md
- fixed the lack of a closing quotation mark in some example codes in Using_Dialogue.md
- changed `get_resource_from_text` to `create_resource_from_text` in the docs page since `get_resource_from_text` no longer exists in the latest version
- changed `parser.queue_free()` to `parser.free()` in dialogue_manager.gd since `queue_free()` does not exist in `parser` as it is not a node, although I am unsure if simply changing it to `free()` is the best solution.
=> Improvement on docs / fixing parser.queue_free()

addons/dialogue_manager/views/main_view.tscn
Literally just changed the solid HBoxContainer to HSplitContainer so i can resize my title list. I didn't like how i couldn't so here we are. You can do what you want with this i just thought i'd share
Thanks for the great addon :)
=> Made title panel resizeable

addons/dialogue_manager/dialogue_manager.gd, docs/Translations.md, examples/point_n_click_balloon/balloon.gd
Made a small change to how the translation func works. Previously it was accidentally returning the translation_key (line id) when it didn't equal the english text (ideally you would want to return that only when the text and line id/translation key were the same), otherwise you want to get the localized text related to that id. This issue wouldn't show up if you weren't using line ids.
=> Change how translations find keys

addons/dialogue_manager/components/settings.gd
The parameter `include_all_responses` isn't in the settings dictionary, causing an error when it's toggled.
Tested using 4.0.2 stable.
=> Fix settings bug with include_all_responses

addons/dialogue_manager/dialogue_manager.gd
The function would crash when run due to a typo causing it to try to find the non-existent key "property" on the results for get_property_list().
=> Fix thing_has_property function

addons/dialogue_manager/dialogue_manager.gd
Calling `erase` on an array wasn't returning before hitting the catchall fail assertion. This change adds a null return after erasing.
=> Fixes issue with calling erase on arrays

addons/dialogue_manager/dialogue_label.gd
This marks the `skip_action` input as being handled. That should remove any double input handling if the `skip_action` value is set to the same as the one for advancing to the next line (eg. `ui_accept`).
=> Mark skip action as handling input

addons/dialogue_manager/example_balloon/example_balloon.gd
This furthers the work in #207 and makes sure response GUI events are set as handled as well.
=> Mark response GUI events as handled

Dialogue Manager.csproj, addons/dialogue_manager/dialogue_manager.gd
This makes the `DialogueManager` singleton available earlier (in `_init` instead of `_ready`) so that other scripts can connect to signals without waiting for the node to be ready.
closes #210
=> Make the singleton available earlier

addons/dialogue_manager/dialogue_label.gd
Stop `finished_typing` from emitting twice when skipping dialogue.
Fixes #215
=> Stop emitting finished_typing twice

addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot
Hey there! This PR adds the `Quaternion` type to the list of resolvable types such as `Vector2` and `Vector3`. I understand that this may be used very little but thought it would be good to add as a kind of "why not? I'm using it so what if others need to as well?". If you don't think this is worth adding, I 100% understand.
Thanks!
=> Add `Quaternion` as accepted value type

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/components/settings.gd, examples/test_scenes/TestScene.cs
This adds an async `GetSingleton()` method to the C# wrapper in cases where `Engine.GetSingleton("DialogueManager")` seems to be occasionally null. It works by continually trying to find the singleton until it either loads or fails completely.
Related to #210
=> Add a singleton helper for C#

addons/dialogue_manager/dialogue_label.gd
This stops the type out auto pausing on "." if it's found between two numbers.
Closes #223
=> Skip numbers when auto-pausing

addons/dialogue_manager/dialogue_manager.gd, examples/test_scenes/test_scene.gd
This moves the Singleton registration back into `_ready()` to get rid of the `Script does not inherit from Node` warning.
=> Fix Node inheritance warning

docs/Using_Dialogue.md
The title must be the 2nd argument of the DialogueManager.get_next_dialogue_line function. I fixed the bug in the end of the [Using_Dialogue.md](docs/Using_Dialogue.md).
=> Fix a bug in script in Using_Dialogue.md

addons/dialogue_manager/views/main_view.gd
This sets the dialogue editor to inherit the main code editor smooth scrolling setting.
Closes #232
=> Inherit text editor smooth scroll setting

addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot
This makes the runtime throw an error when a deliberate title is given that doesn't exist.
Fixes #235
=> Make deliberately missing key throw an error

addons/dialogue_manager/dialogue_manager.gd
This fixes calling `emit` on a chained signal directly (eg. `do SomeGlobal.some_signal.emit(some_arg)`)
=> Fixes calling emit on a signal directly

addons/dialogue_manager/DialogueManager.cs
Explicitly mark types which can be nullable as nullable so that projects with C# nullability checks enabled can use this plugin without getting compile errors.
=> Add type nullability

addons/dialogue_manager/dialogue_label.gd
This makes sure any mutations at the end of lines get run when the typing out finishes.
=> Make sure end of line mutations get run

addons/dialogue_manager/dialogue_label.gd, addons/dialogue_manager/example_balloon/example_balloon.gd
This adds click handling to the example balloon to skip typing of the dialogue label.
=> Adds clicking to skip typing in the example balloon

addons/dialogue_manager/dialogue_manager.gd
This allows for calling signal references directly instead of just string names (eg. `do emit(some_signal)` instead of `do emit("some_signal")`).
Closes #251
=> Allow non-string signal names in emit

addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/dialogue_manager.gd
This fixes using deep references when using dictionary literals (eg `do some_function({ "some_key": SomeAutoload.SomeEnum.SomeValue })`.
Fixes #252
=> Fix enum referencing in dictionaries

addons/dialogue_manager/dialogue_manager.gd
This changes how methods are checked on state objects to more tightly check for non-idiomatic GDScript styles before resorting to checking for C# methods.
=> Allow camel case in GDScript methods

addons/dialogue_manager/components/dialogue_cache.gd, addons/dialogue_manager/import_plugin.gd, addons/dialogue_manager/plugin.gd, addons/dialogue_manager/views/main_view.gd
This changes how the dialogue file cache is built and maintained. It no longer writes to the file system and no longer does a total rebuild at any time after the initial boot. Dependency detection and recompiling is now deferred and batched which will hopefully speed things up in large projects.
Related to #265
=> Rework dialogue cache

addons/dialogue_manager/components/parser.gd, docs/Writing_Dialogue.md
This adds support for indented newlines in dialogue lines. For example, these two snippets would be equivalent:
```
Coco: This is the first line.
This line would show up below it in the same balloon.
And even this line.
```
and
```
Coco: This is the first line.\nThis line would show up below it in the same balloon.\nAnd even this line.
```
=> Add support for indented newlines

addons/dialogue_manager/dialogue_line.gd, addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/dialogue_response.gd, docs/API.md
This adds an `id` property to `DialogueLine` and `DialogueResponse` objects.
Related to #273
=> Add IDs to lines and responses

addons/dialogue_manager/dialogue_manager.gd
The lines that are automatically generated from responses have no id, which causes crash in `get_next_dialogue_line()`
Example:
```gdscript
NPC: line
- Player: response
NPC: answer
```
=> Fix issue with generated lines missing IDs

addons/dialogue_manager/example_balloon/example_balloon.gd
When the dialogue is advanced in the example baloon by clicking with the mouse, the subsequent release of the mouse button causes the next line to be always skipped.
By adding a check if the button is pressed before skipping, this can be avoided.
=> Fixed skip_typing() triggered by mouse release in example balloon

addons/dialogue_manager/import_plugin.gd
This bumps the internal compiler version to ensure that compiled resources have line IDs.
=> Bump compiler version

addons/dialogue_manager/dialogue_label.gd, examples/visual_novel_balloon/balloon.gd
This resets the `visibility_ratio` when starting a `type_out` on the `DialogueLabel`.
=> Reset DialogueLabel visibility ratio on type_out

docs/CSharp.md
Just two small typo fixes to the CSharp docs
=> Fix two typos in CSharp docs

addons/dialogue_manager/components/code_edit_syntax_highlighter.gd, addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/components/resolved_tag_data.gd, addons/dialogue_manager/dialogue_line.gd, addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/dialogue_response.gd, addons/dialogue_manager/import_plugin.gd, docs/API.md, docs/Writing_Dialogue.md, examples/dialogue.dialogue.import, examples/dialogue_for_csharp.dialogue.import, examples/dialogue_for_point_n_click.dialogue.import, examples/dialogue_for_visual_novel.dialogue.import, examples/dialogue_with_input.dialogue.import
This adds support for line/response tags. They get processed at compile time (as opposed to BBCode and RichTextEffects that get processed at run time). 
To define tags, specify something like `[#tag1, #tag2]` on a dialogue line or response and they will be available as `.tags` (a `PackedStringArray`) on the line or response.
Related to #272
=> Add line tags

addons/dialogue_manager/components/code_edit.gd, addons/dialogue_manager/dialogue_manager.gd, docs/Settings.md, docs/Writing_Dialogue.md
This adds a fallback for when the "Test dialogue" button is pressed but there is no active title to start from.
Closes #296
=> Fix running test scene when there is no active title

addons/dialogue_manager/dialogue_line.gd, addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/dialogue_response.gd
This moves the `tags` fallback to happen earlier.
=> Change where the tags fallback resolves

addons/dialogue_manager/components/code_edit.gd
This changes the comment toggler to check for a proper selection.
Fixes #305
=> Fixes comment toggling of empty lines

addons/dialogue_manager/dialogue_manager.gd
This makes the `load` method available directly in dialogue mutation calls.
=> Make load available as a built-in method

addons/dialogue_manager/dialogue_reponses_menu.gd, addons/dialogue_manager/example_balloon/example_balloon.tscn, addons/dialogue_manager/example_balloon/small_example_balloon.tscn
This swaps out the `RichTextLabel` responses for `Button` nodes which should make them simpler to restyle (previously the styles lived on `ResponseLabel` which wasn't easy to find).
=> Swap RichTextLabel responses for Buttons

addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/dialogue_manager.gd, docs/Writing_Dialogue.md
This adds support for using the `%` syntax for goto lines.
To go to one randomly of a set of titles you might have something like:
```
Nathan: Let's go to a random title.
% => first_title
% => second_title
% => third_title
```
Closes #314
=> Make goto lines randomisable

addons/dialogue_manager/components/parser.gd
When using blocks that incur a new indent level, using empty but non-indented lines messed up the parent assignment process, thus resulting in unwanted behavior most of the time.
For example:
```
~ start
Nathan: Hi, I'm Nathan and this is Coco.
Coco: Meow.
Nathan: Here are some response options.
- First one
Nathan: You picked the first one.
- Second one
Nathan: You picked the second one.
- Start again => start
- End the conversation => END
Nathan: I hope this example is helpful.
Coco: Meow.
=> END
```
Just adding this one simple empty line to the default example made the `next()` call on line 8 to go to a premature end.
The fix is simply not to pop the parent stack when encountering an empty line. One other fix I considered was to move up the `is_line_empty(raw_line)` check so that it is …
=> Fix: empty non-indented lines mess up parent stack

addons/dialogue_manager/dialogue_label.gd, docs/API.md
This adds a `skipped_typing` signal for when the `DialogueLabel` skips typing.
Closes #318
=> Add a skipped_typing signal

addons/dialogue_manager/components/parser.gd
There are currently two issues with the new random weight:
-----
> Separation between dialogues and goto types didn't work properly:
> ```
> ~ start
> 
> % Random 1
> % =>< something
> % Random 2
> % Random 3
> 
> => END
> 
> ~ something
> 
> => END
> ```
> 
> 1 was on its own, the goto didn't match with the 1, however 2 and 3 matched with the goto because of the lazy `and` evaluation.
-----
> Siblings `next_id` was not set properly for middle-of-the-pack siblings:
> ```
> ~ start
> 
> % Random 1
> % Random 2
> % Random 3
> % Random 4
> 
> => END
> ```
> 
> 1 being the original, its `next_id` was properly set, as well as 4 because of it being the last.
> However 2's `next_id` was still 3, and 3's was 4. So you could have several dialogues being displayed one after the other.
-----
Both …
=> Fixed random weight issues

addons/dialogue_manager/dialogue_manager.gd, docs/Using_Dialogue.md
This adds the ability to specify how a game determines what the "current scene" is. By default it assumes `get_tree().current_scene` or the last child of `get_tree().root`.
To make a custom function for determining the current scene, pass a callable to `DialogueManager.get_current_scene`:
```gdscript
DialogueManager.get_current_scene = func():
return that_scene
```
=> Allow for custom current_scene implementations

addons/dialogue_manager/dialogue_label.gd, addons/dialogue_manager/dialogue_reponses_menu.gd, addons/dialogue_manager/example_balloon/example_balloon.tscn
This adds an optional export property to `DialogueResponsesMenu`s for specifying a response template. If provided, the template will be duplicated for each response instead of using the default `Button` control.
Closes #328
=> Allow for specifying a response template

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/dialogue_manager.gd, docs/CSharp.md, examples/test_scenes/TestScene.cs
This simplifies [how signals are handled in C#](https://github.com/nathanhoad/godot_dialogue_manager/blob/efe7da33a1816238f6e65d97895bc51e954780e3/docs/CSharp.md#signals).
You can now do something like:
```csharp
DialogueManager.DialogueEnded += (Resource dialogueResource) =>
{
// ...
};
```
=> Simplify signal handling in C#

addons/dialogue_manager/test_scene.gd
This adds a workaround for referencing the `DialogueManager` autoload before the addon has been enabled in Project Settings.
=> Add workaround for first-load script error

addons/dialogue_manager/dialogue_manager.gd
This adds a workaround for C# sometimes forgetting that some classes exist.
=> Add a workaround for C# forgetting classes

addons/dialogue_manager/dialogue_manager.gd
This adds a workaround for C# occasionally having a problem with static methods in GDScript.
=> Add workaround for C# forgetting static method

addons/dialogue_manager/dialogue_label.gd
This fixes an issue where the wait index wasn't being reset to subsequent `wait` calls were being ignored.
Fixes #353
=> Reset wait index when starting to type

addons/dialogue_manager/components/code_edit_syntax_highlighter.gd, addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/components/resolved_line_data.gd, addons/dialogue_manager/dialogue_line.gd, addons/dialogue_manager/dialogue_manager.gd, docs/Writing_Dialogue.md
This fixes an issue where conditionals that were right next to each other would fail to execute properly (it also adds inline `[else]`).
Fixes #352
=> Fix conjoined conditionals

addons/dialogue_manager/dialogue_manager.gd
This fixes a crash when using the mono version of Godot without a dotnet solution file.
=> Fix crash in mono if missing dotnet solution file

addons/dialogue_manager/plugin.gd
This hopefully quiets the occasional `nonexistant function 'get_files_with_errors' in base 'Nil'` errors that are showing up for some people.
=> Add a load guard to the build cache

addons/dialogue_manager/dialogue_label.gd
This fixes an issue where setting the `DialogueLabel` seconds per step to 0 would result in the `finished_typing` signal emitting before it could be connected.
=> Stop finished_typing emitting too soon

addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/constants.gd, addons/dialogue_manager/editor_translation_parser_plugin.gd
Fixes #366.
Introduces a new type constant to make sure the parser doesn't lump import lines with general dialogue lines.
Uses a small manual quoting on the lines added to the POT files. Godot 4.2 will not double the backslash, and will escape the quotes on its own so it is forward-compatible.
=> Fix POT generation

examples/point_n_click_balloon/balloon.gd, examples/portraits_balloon/balloon.gd, examples/visual_novel_balloon/balloon.gd
Hi Nathan,
Found and fixed a small bug. The "ui_accept" input is never marked as handled after the user chooses a "response" which itself has no responses. On my end, dialogue was getting re-entered in a loop as the same "unhandled" input exited dialogue but remained unhandled, and so was handled by my game's unhandled-input-handler.
The fix was simple. The same line of code that was added to `_on_balloon_gui_input_` function, for what I imagine what a similar problem, is added to `_on_response_gui_input_`. 
I added the fix to the 3 examples I could find. Sadly, Github's web interface insisted each change was a commit. If you want to merge, please squash them if you know how!
=> Mark response input as handled in examples

addons/dialogue_manager/components/settings.gd, addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, addons/dialogue_manager/l10n/zh.po, addons/dialogue_manager/l10n/zh_TW.po, addons/dialogue_manager/plugin.gd, addons/dialogue_manager/test_scene.gd, addons/dialogue_manager/views/settings_view.gd, addons/dialogue_manager/views/settings_view.tscn, docs/API.md, docs/Settings.md, docs/Using_Dialogue.md
This adds a [`show_dialogue_balloon`](https://github.com/nathanhoad/godot_dialogue_manager/blob/ac819bc0168732d43a93bb98377ec3b5ae2a7909/docs/API.md#func-show_dialogue_balloonresource-dialoueresource-title-string---extra_game_states-array-----node) method to the Dialogue Manager which can be configured in settings to show your custom balloon. This is essentially a shortcut to implementing a method that adds the balloon to the scene tree. If you need more complicated logic then it's still recommended to implement it yourself.
=> Add `show_dialogue_balloon()` method

addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/components/resolved_line_data.gd, addons/dialogue_manager/dialogue_line.gd, addons/dialogue_manager/example_balloon/example_balloon.gd, examples/portraits_balloon/balloon.gd, examples/visual_novel_balloon/balloon.gd
When 'Project Setting -> GDScript -> Unsafe Cast' enabled, the `DialogueLine::time` is a variant, the cast from variant to String will lead to a warn.
To keep the variable type of the `DialogueLine::time` consistent throughout, the initial value of time is set to the empty string "".
=> Set null value of time from null to ""

addons/dialogue_manager/components/parser.gd
This fixes an issue where variables that had names that began with "true", "false", etc would throw compilation errors.
=> Allow variables to start with keywords

addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, addons/dialogue_manager/views/settings_view.gd, addons/dialogue_manager/views/settings_view.tscn
This moves the "custom test scene" setting into a new "Advanced" tab in settings to help alleviate some confusion between it and the custom balloon setting. Setting a custom test scene will now show a warning if the selected scene doesn't extend `BaseDialogueTestScene`.
=> Remove some confusion around custom test scene

addons/dialogue_manager/components/parser.gd
This rearranges the compiler tokens to make sure "not" is processed before variables.
Fixes #385
=> Fix compiler issue with "not" keyword

addons/dialogue_manager/dialogue_response.gd
Unifying the interface for both `DialogueLine` and `DialogueResponse` when it comes to tags.
Will allow people to get the tag value within the `ResponsesMenu`.
=> Add get_tag_value() to DialogueResponse

addons/dialogue_manager/dialogue_reponses_menu.gd
This allows for more custom response templates when using the `DialogueResponsesMenu` node. If the template has a `response` property then it will be given the whole response object.
=> Allow response templates to accept whole response

addons/dialogue_manager/dialogue_label.gd, docs/API.md
Allow the user to set the length of pauses, don't spit an error when the skip input action isn't found, and run the DialogueLabel script in-editor.
=> Improve DialogueLabel flexibliity

addons/dialogue_manager/dialogue_label.gd, docs/API.md
This allows for auto pause characters (eg. ".") on the `DialogueLabel` to be skipped if they are followed by given characters (eg. ")").
=> Allow auto pause characters to be skipped

addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/l10n/en.po, tests/test.gd, tests/test_basic_dialogue.gd
This fixes the missing error when indenting a title.
Fixes #404
=> Fix missing error when indenting titles

addons/dialogue_manager/components/parser.gd, tests/test_extracting_markers.gd
It seems `String.erase()` wasn't available in Godot 4.0 so this replaces it with a couple of `substr`s.
Fixes #411
=> Keep compatibility with Godot 4.0

addons/dialogue_manager/components/dialogue_cache.gd, addons/dialogue_manager/import_plugin.gd
This fixes an infinite import loop when using circular dependencies.
Fixes #416
=> Fix recursive importing for circular dependencies

addons/dialogue_manager/dialogue_label.tscn
This changes the default `DialogueLabel` text shaping to only show images as the typing out cursor gets to them.
=> Show images as they are typed out

addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, addons/dialogue_manager/plugin.gd, addons/dialogue_manager/settings.gd, addons/dialogue_manager/views/settings_view.gd, addons/dialogue_manager/views/settings_view.tscn
This adds an advanced option for opening dialogue files in an external editor (if configured in Editor Settings).
**⚠ Note: Syntax highlighting and detailed error checking is not supported in external editors.**
Closes #410
=> Add setting for using external editor

addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/plugin.gd, addons/dialogue_manager/settings.gd, project.godot
This makes sure dialogue settings are present in the Project Settings window once the plugin has been enabled. Previously settings would only be added there once they had been changed in the settings window in the dialogue editor.
Closes #432
=> Prepare settings when enabling plugin

addons/dialogue_manager/dialogue_label.gd, docs/API.md
_If this is a change to the compiler then make sure to add/update any tests that may be affected._
_If this change needs updates to the documentation then make sure you've made those changes too._
- Adding an additional export variable to define abbreviations
- Logic to check if recent visible characters make up one of the defined abbreviations. If so, and "." is a `pause_character`, skip pausing
My game involves many doctors, and has a formal hospital setting. As a result, there was a lot of additional pausing after every `Dr. Foo` and `Mrs. Bar`. By doing a short look back, we can determine if an abbreviation was …
=> Adding support for skipping pauses after "." when using abbreviations

tests/tests.gd
This forces the locale when running tests to be "en" so that any tested dialogue lines match the text as written and don't get auto translated.
Closes #441
=> Force en locale for tests

addons/dialogue_manager/views/settings_view.gd
This fixes the "Array is in read-only state" error that sometimes shows up when setting state shortcuts.
=> Fix "Array is in read-only state" error

addons/dialogue_manager/dialogue_label.gd, addons/dialogue_manager/settings.gd
This removes the `for` iterator type hints that were recently added because they break compatibility with Godot 4.0
=> Restore compatibility with Godot 4.0

addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/plugin.gd
This swaps out String `erase` for a combination of `left` and `right` to restore compatibility with Godot 4.0 where `erase` didn't exist on Strings.
=> Swap out String method missing from Godot 4.0

addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, addons/dialogue_manager/settings.gd, addons/dialogue_manager/views/main_view.gd, addons/dialogue_manager/views/settings_view.gd, addons/dialogue_manager/views/settings_view.tscn, docs/Settings.md
This adds advanced options to include the character name and doc-style comments (eg. `## This is a comment`) to translation exports.
Characters will be in a column labelled `_character` and notes will be under `_notes`. If the file being exported over already has either of these columns the setting will be assumed to be on and write characters/notes accordingly.
_**Note:** Depending on your version of Godot, you may see errors in the Output tab (and for older Godot 4s you may end up with invalid translation import files._
Closes #323 
Closes #440
=> Include character names and notes in translations

addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, tests/state_for_tests.gd, tests/test_state.gd
This adds a workaround for Godot's typed array conversion when using some array types for mutation arguments.
_*Note:* Only some typed arrays (`String`, `int`, `float`, `Vector2`, and `Vector3`) are supported. Complex types will throw an error and suggest using just `Array` instead._
Fixes #458
=> Allow some array types as mutation args

addons/dialogue_manager/constants.gd, addons/dialogue_manager/dialogue_manager.gd
This moves all runtime assertions to be behind conditional checks so that their message isn't evaluated early.
Related to #459
=> Defer evaluating assert messages

addons/dialogue_manager/example_balloon/example_balloon.tscn
This adds a workaround to a seemingly elusive issue that was affecting a small number of users - the example balloon panel would sometimes be fully transparent leaving the white text hard to read against a bright game background.
After a lot of trial and error (I haven't been able to replicate the issue myself) it looks like the solution was to re-arrange the example balloon scene tree and then apply a Clip+Draw on the `Panel` node.
=> Add possible workaround for invisible panel issue

addons/dialogue_manager/dialogue_manager.gd
This swaps `type_convert` for the older (and deprecated) `convert` that works in Godot before 4.2.
Fixes #466
=> Use older type convert method for older Godot 4s

addons/dialogue_manager/components/parser.gd, docs/Writing_Dialogue.md, tests/test_state.gd
This allows for lines that start with `if`, `elif`, and `else` to be escaped to dialogue instead of being parsed as conditionals. To escape a condition line, prefix it with `/` (eg. `/if this line is dialogue`).
=> Escape keyword line starts

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/dialogue_manager.gd, docs/API.md, examples/test_scenes/TestScene.cs, examples/test_scenes/test_scene.gd
This adds `show_dialogue_balloon_scene` (and `ShowDialogueBalloonScene` for C#) which allows passing a scene path or packed scene or node to show as the dialogue balloon.
=> Add method for showing a specific dialogue balloon

Dialogue Manager.csproj, Dialogue Manager.sln, addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/views/settings_view.gd
This automatically reverts the custom balloon path back to the example balloon if the custom balloon scene file no longer exists.
=> Revert custom balloon path if it no longer exists

addons/dialogue_manager/example_balloon/ExampleBalloon.cs
This makes the C# custom balloon template clean up its `mutated` signal handler when freeing the balloon.
=> Make the C# balloon clean up mutation signal

addons/dialogue_manager/dialogue_manager.gd
I was trying to create a function that receives a signal as one of the arguments, but the signal gets converted to string by the time the function is called. Something like:
```gdscript
func wait_for_stuff_to_happen(something_happened: Signal, target: Node):
target.do_stuff()
await something_happened
target.do_more_stuff()
```
It would be called from dialogue like `do wait_for_stuff_to_happen(...)`.
Changing the conversion to `resolve_signal` allowed me to pass the signal, so I thought it might be a good idea to change it. If it isn't or it should be handled in a different way let me know.
=> Allow passing Signal arguments to functions

addons/dialogue_manager/DialogueManager.cs
This fixes an issue where mutation methods that were defined in a parent class to the current scene weren't visible to the dialogue runtime.
Related to #487
=> Allow inherited mutations in C#

addons/dialogue_manager/components/code_edit_syntax_highlighter.gd, addons/dialogue_manager/dialogue_manager.gd
This fixes comparing `null` to variables whose value is actually `null`.
=> Fix null comparisons when variable value is null

addons/dialogue_manager/utilities/builtins.gd
This removes a few niche constants from `Vector3` that aren't available in older Godot 4s.
=> Remove constants that aren't backwards compatible

addons/dialogue_manager/settings.gd, addons/dialogue_manager/views/main_view.gd
This will remember which files were open in the previous session (if the "restore scripts on load" editor setting is enabled).
Closes #493
=> Remember which files were open in previous session

addons/dialogue_manager/dialogue_label.gd
This moves the `finished_typing` signal on the `DialogueLabel` to happen later.
Related to #497
=> Call finished_typing signal later

addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/utilities/builtins.gd, examples/state.gd
This better handles builtin `resolve_method` calls when the method doesn't exist. It will now fall back to the standard "not found in any states" error.
Fixes #498
=> Fix order of resolves for state

addons/dialogue_manager/dialogue_manager.gd
This defers emitting `dialogue_ended` until `get_next_dialogue_line`/`GetNextDialogueLine` can finish returning.
Related to #499
=> Defer emitting dialogue_ended

addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/dialogue_manager.gd
Previously, if a title was found between a line and responses the `passed_title` signal wouldn't be emitted.
This change also makes sure responses found through a jump after a line will now be attached to the line.
For example:
```
Nathan: Will you do it?
~ responses
- Yes
- No
Nathan: Pleeeaaase...
=> responses
Nathan: Great!
```
The "Pleeeaaase..." line will now have "Yes" and "No" attached to it.
Fixes #503 
Fixes #505
=> Emit passed_title if title found between line and responses

addons/dialogue_manager/utilities/builtins.gd
This brings back Godot 4.1 Vector3 constants and still guarantees backwards compatibility with Godot 4.0
Reverts 8b2aa57ea413319d0fbb6c6facbb8d0e1628ff0f
=> Bring back Godot 4.1 Vector3 Constants

addons/dialogue_manager/dialogue_label.gd, docs/Writing_Dialogue.md
This makes inline mutations behave the same as regular mutations in that if they use `await` in their implementation they will pause execution of dialogue (in this case typing dialogue) until they resolve.
Related to #515
=> Allow awaiting inline mutations

addons/dialogue_manager/dialogue_label.gd
How to replicate:
I found an edge case where you get an out of bounds exception while typing out if the text translates to one shorter. It seems the "visible_characters" property can be larger than the "parsed_text" when the text is localized.
How to replicate:
1. Create a dialogue label with auto-translate enabled
2. Change the TranslationServer language while typing out. 
> For example English: ```Clive: In the year 1988...``` to Spanish: ```Clive: En el año 1988```
=> Avoid outofbounds when DialogueLabel changes language while typing

addons/dialogue_manager/components/code_edit_syntax_highlighter.gd, addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/dialogue_manager.gd, docs/Writing_Dialogue.md, tests/test_state.gd
This adds support for not having to wait for mutations that use `await`. To do so, add a "!" to "do" - eg. `do! something_that_awaits()`
=> Allow non-blocking mutations with "do!"

addons/dialogue_manager/components/parser.gd, tests/test_state.gd
This makes the new `do!` mutations work for inline mutations too. If your mutation uses `await` but you don't want to wait for it (eg. if it's just kicking off an animation to run while typing) then use `[do! some_mutation]`.
=> Allow await skipping for inline mutations

addons/dialogue_manager/dialogue_manager.gd, tests/test_basic_dialogue.gd
Fixes a bug introduced in #528 that causes an array index out of bounds exception when attempting to call a vararg method that has optional arguments and those optional arguments are not provided.
=> Fix out of bounds without optional arguments

addons/dialogue_manager/DialogueManager.cs
This stops C# methods that use `async` without encountering an `await` from infinitely blocking flow.
Fixes #537
=> Fix C# async methods returning without await

addons/dialogue_manager/components/find_in_files.gd, addons/dialogue_manager/components/find_in_files.tscn, addons/dialogue_manager/components/search_and_replace.gd, addons/dialogue_manager/components/search_and_replace.tscn, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, addons/dialogue_manager/views/main_view.gd, addons/dialogue_manager/views/main_view.tscn
This adds support for finding and replacing text across all dialogue files.
Closes #424
=> Add support for find/replace across files

addons/dialogue_manager/plugin.gd
This is kind of a hack to stop the project showing as unsaved just after it has been opened and nothing has changed yet.
Closes #536
=> Prevent project showing as unsaved when opening

addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/dialogue_manager.gd
This fixes an issue when a character name was a variable in a auto-line response prompt. For example, given this dialogue and assuming `player_name` was an available variable with a value of "Coco":
```
Nathan: Here are some responses.
- {{player_name}}: Some response.
- {{player_name}}: Another response.
```
Previously, this would resolve the prompt text to be something like `Some response. Coco` but will now correctly resolve to just `Some response.`.
=> Fix character replacements in response shortcuts

addons/dialogue_manager/components/parser.gd
This fixes an issue when using a `=><` jump to a snippet at the end of a file that doesn't end with an explicit `=> END`. Previously it would assume an `=> END!` (end conversation) but it will now correctly assume an `=> END` (end block) so that the snippet will return to where it jumped from.
Related to #532
=> Fix EOF end being too forceful

addons/dialogue_manager/components/code_edit.gd, addons/dialogue_manager/plugin.gd, addons/dialogue_manager/views/main_view.gd
This changes the keyboard shortcuts (eg. toggle comment) to use the native Godot editor shortcuts where possible.
Godot doesn't seem to expose the shortcuts directly so this attempts to read the `editor_settings-4.tres` resource for any shortcut overrides.
Related to #549
=> Use editor shortcuts where possible

addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/import_plugin.gd, examples/dialogue.dialogue.import, examples/dialogue_for_csharp.dialogue.import, examples/dialogue_for_point_n_click.dialogue.import, examples/dialogue_for_visual_novel.dialogue.import, examples/dialogue_with_input.dialogue.import, tests/test_basic_dialogue.gd
This fixes an issue where titles wouldn't pass through another title if it was directly after it.
Fixes #548
=> Allow titles to follow titles

docs/API.md, docs/Settings.md, docs/Using_Dialogue.md
Fixes minor typo in documentation and corresponding markdown links.
=> Fix typos in documentation

addons/dialogue_manager/dialogue_reponses_menu.gd
This changes the `DialogueResponsesMenu` to extend the more generic `Container` node so that it can be used with any kind of container.
Closes #557
=> Make responses menu base type more flexible

addons/dialogue_manager/dialogue_manager.gd
When using gettext translations, [Godot supports both `.po` and `.mo` files.](https://docs.godotengine.org/en/stable/tutorials/i18n/localization_using_gettext.html#using-binary-mo-files-useful-for-large-projects-only)
When guessing for a translation source, Dialogue Manager did not consider sources that ended in `.mo` as gettext sources. So the lines were not translated, and only the translation key was displayed.
This PR adds the auto-guessing for `.mo` files.
=> Fix: add .mo extension to PO translation behavior

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/example_balloon/ExampleBalloon.cs, addons/dialogue_manager/example_balloon/example_balloon.gd, examples/csharp_balloon/Balloon.cs
This changes the example balloon so that when it detects a locale change it will update the dialogue label to show the text in the new language. 
⚠ _This comes with the caveat that inline mutations will possibly be run twice if the locale is swapped mid-typing as there is no way of knowing if the new language has the mutations at the same indices._
Closes #565
=> Update the Dialogue Label when the locale changes

addons/dialogue_manager/settings.gd
This should make the dotnet detection a bit more forgiving for when people are using the mono build of Godot but not using C#.
=> Make dotnet detection more forgiving

addons/dialogue_manager/utilities/builtins.gd
This adds support for using `String` methods in variable substitution and mutations.
=> Add support for String methods in mutations

addons/dialogue_manager/example_balloon/example_balloon.gd, project.godot
This makes sure the label reference in the example balloon is ready before handling locale changes (it appears Godot 4.3 has an earlier notification than Godot 4.2).
=> Ensure label is ready before locale change

addons/dialogue_manager/components/code_edit.gd, addons/dialogue_manager/views/main_view.gd
This fixes an upcoming issue with Godot 4.3 where a new method has been added to `TextEdit` that clashes with one in the dialogue text editor.
=> Fix a CodeEdit method name clash

addons/dialogue_manager/DialogueManager.cs
updated ResolveThingMethod() to check if the args is assignable from a derived type. This should allow passing through any custom type as a parameter into a mutation in the dialogue. (this mainly aims at fixing methods that return a Task)
Fixes this issue:
`E 0:00:02:0901   object System.Convert.ChangeType(object, System.Type, System.IFormatProvider): System.InvalidCastException: Object must implement IConvertible.
<C++ Error>    System.InvalidCastException
<C++ Source>   :0 @ object System.Convert.ChangeType(object, System.Type, System.IFormatProvider)
<Stack Trace>  :0 @ object System.Convert.ChangeType(object, System.Type, System.IFormatProvider)
DialogueManager.cs:181 @ void DialogueManagerRuntime.DialogueManager+<ResolveThingMethod>d__36.MoveNext()
:0 @ void …
=> Fix C# mutation handling derived types in args

addons/dialogue_manager/components/code_edit_syntax_highlighter.gd, addons/dialogue_manager/components/parser.gd
This adds support for using `StringNames` (eg. `set some_variable = &"something"`).
Closes #585
=> Add support for StringNames

addons/dialogue_manager/components/code_edit.gd, addons/dialogue_manager/components/code_edit_syntax_highlighter.gd, addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/dialogue_resource.gd, addons/dialogue_manager/editor_translation_parser_plugin.gd, addons/dialogue_manager/import_plugin.gd, addons/dialogue_manager/plugin.gd, addons/dialogue_manager/test_scene.gd, addons/dialogue_manager/views/main_view.gd, addons/dialogue_manager/views/settings_view.gd
This adds explicit loading of class references to hopefully get around the initial loading order in Godot 4.x.
=> Add explicit class references

addons/dialogue_manager/components/code_edit.gd, addons/dialogue_manager/plugin.gd
This adds a shortcut for deleting the current line. The shortcut itself is taken from Godot's code editor settings.
Closes #605
=> Add shortcut to delete current line

addons/dialogue_manager/views/main_view.gd
This fixes an issue where the open buffer cache gets out of sync when a dialogue file has been moved.
Fixes #609
=> Update open buffers when file is moved

addons/dialogue_manager/components/parser.gd
This PR fixes an issue where the syntax highlighter highlights all istances of the "using" string in the dialogue files. The issue is demonstrated in the screenshot below:
=> Fix incorrect syntax highlighting on 'using' keyword

addons/dialogue_manager/dialogue_label.gd, addons/dialogue_manager/example_balloon/example_balloon.gd
This stops mutation being re-run if a skip action was requested while waiting for a mutation.
Fixes #591
=> Stop re-running mutations if skipping mid mutation

addons/dialogue_manager/plugin.gd, addons/dialogue_manager/settings.gd
This adds a project setting to turn off the startup unsaved project indicator suppression.
=> Add setting to turn off startup unsaved indicator

addons/dialogue_manager/dialogue_manager.gd
When profiling my game I found a big spike when initializing a dialogue that came from an anonymous lambda being called 500+ times in one frame.
I traced this back to the `resolve_thing_method()` function in DialogueManager. It uses a filter on a get_method_list array to find the method with the correct name. It seems that can get slow when done for a lot of different methods, so I made a new method that caches the needed information to a dictionary the first time it runs, and uses the cached information in subsequent calls if it's already cached or adds to the cache if it isn't.
This change greatly alleviated the big lag spike I was experiencing.
No tests failed, and no change is needed to the documentation.
=> Use cache when checking for state methods

addons/dialogue_manager/components/search_and_replace.gd
When doing a search while editing dialogue by pressing `Ctrl+f` and typing `potato` results in `fpotato`, at least when using Linux (gnome). Adding `set_input_as_handled` has fixed it for me (and hopefully hasn't broken anything else).
=> Set handled when using shortcut to avoid unwanted input

addons/dialogue_manager/plugin.gd
This makes Godot 4.1 ignore the `save_all_scenes` method that was added to `EditorInterface` in Godot 4.2.
=> Ignore missing "save_all_scenes" in Godot 4.1

addons/dialogue_manager/constants.gd
Fixes #642. 
New orphaned nodes were being created in `constants.gd`, specifically the `translate()` function, in order to assemble the `base_path` string. 
This PR creates a temp_node uses it in the creation of `base_path` then frees it.
=> Free orphan nodes created in constants.gd

addons/dialogue_manager/dialogue_label.gd
Fix #646 
I added a pad_decimals(0) to the check, so now also numbers that have 0 after the dot will not autopause anymore.
=> Fix not auto pausing if a "." is between two numbers and the second number is 0 (#646)

addons/dialogue_manager/example_balloon/example_balloon.gd
This adds the `DialogueManagerExampleBalloon` class name to the example balloon so that it can more easily be extended.
=> Add a class name to the example balloon

addons/dialogue_manager/DialogueManager.cs
The field `extra_game_states` was not exposed through a public property on the `DialogueLine` C# class. Added this to make it easier for running dialogue in custom ways from C#.
=> Added public ExtraGameStates property to DialogueLine

addons/dialogue_manager/example_balloon/ExampleBalloon.cs
As explained in https://github.com/nathanhoad/godot_dialogue_manager/issues/589, a workaround is needed because Godot calls a translation notification before the object is loaded. @nathanhoad already did it for GDScript but it doesn't seem to have made it into the C# version
=> Add _Notification event workacround to C# file

addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/dialogue_manager.gd, docs/Writing_Dialogue.md, tests/test_basic_dialogue.gd
This adds support for conditional randomised jumps and randomised lines:
Conditions for randomised lines go in square brackets after the `%` and before the line's content:
```
% => some_title
%2 => some_other_title
% [if SomeGlobal.some_condition] => another_title
```
Closes #659
=> Add support for conditions on randomised lines

addons/dialogue_manager/plugin.gd
This removes the `DialogueManagerExampleBalloon` class name when using the "copy example balloon" tool.
=> Remove example balloon class on copy

docs/API.md, docs/CSharp.md, docs/Example_Balloons.md, docs/FAQ.md, docs/Settings.md, docs/Translations.md, docs/Using_Dialogue.md, docs/Writing_Dialogue.md
Updated the documentation with improved punctuation for better readability and fixed missing backtick/fullstop and occasional incorrectly used words such as, _"with" instead of "at"_, _"handling" instead of "handle"_, _"as" instead of "has"_, and _"you" instead of "your"_.
=> Assorted documentation changes/fixes

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/dialogue_manager.gd
This addresses an issue where calls to `DialogueManager.GetNextDialogueLine` within the same tick would all return the value from the first request.
=> Allow parallel C# next line requests

addons/dialogue_manager/dialogue_manager.gd
This fixes an issue where responses weren't being joined to the current line if they were through a title.
=> Fix response linking through titles

addons/dialogue_manager/components/parser.gd
This fixes an issue where titles were confusing the compiler when parsing conditional flow.
=> Fix mid-block titles breaking conditional flow

addons/dialogue_manager/components/code_edit.gd
In Godot 4.2.2 the dialogue editor would scroll back up to the top of the file when moving a line. This fixes it by simply returning the scroll value back to its initial value (+offset) from the start of the function.
_If this is a change to the compiler then make sure to add/update any tests that may be affected._
_If this change needs updates to the documentation then make sure you've made those changes too._
=> Fix scrolling issue in code edit

addons/dialogue_manager/editor_translation_parser_plugin.gd
When using this king of dialog line:
`Use the sword with {{InputManager.get_bbcode_for_action_and_current_device("attack", true, 15)}}`
POT generated file contains the following string:
```
#: dialogs/timelines/tutorials/box.dialogue
msgid "To move a box, you must stand in front of it and hold {{InputManager.get_bbcode_for_action_and_current_device(\\\"pull\\\", true, 15)}} while moving"
msgstr ""
```
This prevents godot from loading the po/mo files generated by POEdit
This PR removes the redundant backslashes but there may be side effects
=> Remove unnecessary backslash in POT file

addons/dialogue_manager/dialogue_manager.gd
Fixes the behavior of the engine when reading numbers: instead of treating them like variables and attempting to parse them using the current scene, they are passed as-is downstream. Also fixes a typo in the same class.
=> Fix for numbers parsing

addons/dialogue_manager/components/parser.gd, docs/Translations.md
This makes a slight adjustment to differentiating between character and dialogue in dialogue lines for when the line is basically blank (ie. only contains a static line ID).
=> Account for character but no dialogue

addons/dialogue_manager/plugin.gd
In preparation for Godot 4.4 this makes sure example balloon copies get a new UID when copied.
=> Give example balloon copies a new UID

addons/dialogue_manager/plugin.gd
In preparation for Godot 4.4, this ensures that the current example balloon copy has a UID that is unique the original example balloon.
=> Ensure example balloon copy has a unique UID

addons/dialogue_manager/components/dialogue_cache.gd, addons/dialogue_manager/plugin.gd, addons/dialogue_manager/views/main_view.gd
This moves when resources are actually compiled to hopefully avoid clashing with Godot's automatic import process.
Related to #723
=> Delay reimporting to avoid clashes with editor

addons/dialogue_manager/dialogue_manager.gd, docs/API.md
I've added a signal called `dialogue_started(resource: DialogueResource)`
The signal emits when either the example balloon or a custom balloon is created, and dialogue starts.
This signal is more specific and useful to mark when dialogue starts than the existing `title_passed(title)` because it is only emitted once when the dialogue first begins, and includes a reference to the dialogue resource file. This signal pairs very nicely with the existing `dialogue_ended(resource: DialogueResource)` signal.
I have also updated the documentation to include this signal and what it does.
=> Added signal to DialogueManager for when dialogue starts

addons/dialogue_manager/compiler/compiled_line.gd, addons/dialogue_manager/dialogue_manager.gd, tests/test_state.gd
This fixes an issue where compiled condition lines were incorrectly reading a blank sibling reference as existing.
Fixes #740 
Fixes #741
=> Fix "else" being incorrectly required

addons/dialogue_manager/compiler/compilation.gd, tests/test_basic_dialogue.gd
This fixes an issue where titles that were directly after an indent change were not being added to the known titles list.
Fixes #742
=> Fix title not found if after dedent

addons/dialogue_manager/compiler/compilation.gd
This fixes instances where `\n` literals in dialogue were showing up as actual text.
=> Fix newline literals being ignored

addons/dialogue_manager/compiler/compilation.gd, tests/test_responses.gd
This fixes an issue where empty lines were breaking the grouping of responses. Empty lines are only supposed to break the grouping of randomised lines.
=> Fix empty lines breaking response grouping

addons/dialogue_manager/dialogue_manager.gd
updated _bridge_get_new_instance() to pass through the previous get_current_scene value into the temporary C# bridge instance. this fixes an issue where modifying DialogueManager.GetCurrentScene in a C# script would only update the get_current_scene variable in the main instance, and not from the temporary instance created by _bridge_get_new_instance().
=> Keep previous get_current_scene data in C# bridge

addons/dialogue_manager/compiler/compilation.gd, tests/test_state.gd
This fixes an issue where peerless `if` statements where incorrectly grouping to another group's `else` statement.
Fixes #752
=> Fix issue with if grouping with wrong else

addons/dialogue_manager/dialogue_label.gd, addons/dialogue_manager/utilities/builtins.gd, tests/test_dialogue_label.gd
This stops mutations that exist within the same index of a line from clobbering each other.
Fixes #754
=> Fix nestled inline mutations being clobbered

addons/dialogue_manager/compiler/compilation.gd, tests/test_basic_dialogue.gd, tests/test_responses.gd
This fixes an issue that was causing static line ID definitions to be incorrectly consumed by response conditions.
Fixes #755
=> Fix conditional responses with static IDs

addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, addons/dialogue_manager/settings.gd, docs/Settings.md, tests/test_state.gd
This adds a new advanced runtime setting to check for top-level state (ie. extra game states, current scene, autoload shortcuts) naming collisions. When referring to a property/method/signal in dialogue that has multiple possible references a warning will show in the Debugger panel:
Closes #746
=> Add a check for top-level state name collisions

addons/dialogue_manager/example_balloon/ExampleBalloon.cs, addons/dialogue_manager/example_balloon/example_balloon.gd
This updates both the GDScript and C# example balloons to better debounce the `mutated` signal handler.
=> Update example balloons

addons/dialogue_manager/compiler/compilation.gd, addons/dialogue_manager/compiler/compiled_line.gd, addons/dialogue_manager/constants.gd, addons/dialogue_manager/dialogue_line.gd, addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, docs/API.md, docs/Basic_Dialogue.md, tests/test_simultaneous_dialogue.gd
This adds support for concurrent dialogue.
To write lines that are meant to be spoken at the same time as a regular dialogue line you can prefix them with "| ".
```
Nathan: I'll say this.
| Coco: And I'll say this at the same time!
| Lilly: And I'll say this too!
```
=> Add support for simultaneous lines

addons/dialogue_manager/example_balloon/ExampleBalloon.cs
This adds the Example Balloon itself to the list of extra game states in the C# Example Balloon (the GDScript balloon was already doing this).
Related to #759
=> Add missing "this" to C# Example Balloon states

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/dialogue_manager.gd
This adds the `dialogue_started` signal that was missing from the C# wrapper.
=> Add missing "dialogue_started" signal to C#

addons/dialogue_manager/views/main_view.gd
This stops any unsaved buffers from being clobbered by external file changes. Now only the "pristine text" of the open file will be updated.
Related to #768
=> Stop updating unsaved buffer on external change

Dialogue Manager.csproj, addons/dialogue_manager/editor_translation_parser_plugin.gd, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, project.godot, tests/test_simultaneous_dialogue.gd.uid
This uses a new hook in Godot 4.4 to add doc (`##`) comments from dialogue to the POT exports against the relevant line.
=> Add doc comments to POT export

addons/dialogue_manager/dialogue_manager.gd, tests/test_state.gd
This stops the concurrency parsing from modifying the underlying line data dictionary.
=> Stop concurrency modifying line data

addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/example_balloon/ExampleBalloon.cs, addons/dialogue_manager/example_balloon/example_balloon.gd, addons/dialogue_manager/example_balloon/example_balloon.tscn
This simplifies how `show_dialogue_balloon` works to eliminate the need for awaiting `ready` in the balloon itself.
=> Simplify showing balloons

addons/dialogue_manager/plugin.gd
This fixes an issue in Godot 4.4 where cloning the example balloon wasn't generating a new UID for the balloon script.
=> Fix UID generation when copying example balloon

addons/dialogue_manager/dialogue_manager.gd
This fixes an issue when overloading mutation methods in C# when the methods weren't in order of argument count.
Fixes #786
=> Fix issue with overloaded method order in C#

docs/Basic_Dialogue.md, docs/CSharp.md
This adds docs for random inline dialogue and the `DialogueStarted` signal in C#.
=> Add a couple of things missing from docs

docs/Settings.md
Updated the docs to reflect the recent removal of `Include All Responses` from the plugin settings.
Fixes #792
=> Remove Include All Responses from docs

addons/dialogue_manager/components/download_update_panel.gd, addons/dialogue_manager/plugin.gd
This detects the presence of dotnet when enabling the plugin to determine which script should be attached to the example balloon.
Fixes #796
=> Fix initial example balloon attached script

addons/dialogue_manager/compiler/compilation.gd, addons/dialogue_manager/compiler/tree_line.gd
The Dialogue compilation system had a cyclical reference between parent and child that causes the RefCounted to never clean up the resource. This PR decides to make the parent reference weak, which allows RefCounted to be cleaned up by the garbage collector if that's the only remaining reference to a resource.
https://docs.godotengine.org/en/stable/classes/class_refcounted.html
> RefCounted instances caught in a cyclic reference will not be freed automatically. For example, if a node holds a reference to instance A, which directly or indirectly holds a reference back to A, A's reference count will be 2. Destruction of …
=> Fix Cyclical Reference By Making Parent Reference Weak

Dialogue Manager.csproj, addons/dialogue_manager/editor_translation_parser_plugin.gd
This updates the `EditorTranslationParserPlugin` to use the new hook for finding translatable messages.
**Once this is merged, Dialogue Manager will require a minimum of Godot 4.4. As such, I'll be leaving it unmerged until Godot 4.4 is officially released.**
Closes #798
=> Update EditorTranslationParserPlugin signature

addons/dialogue_manager/compiler/compilation.gd, addons/dialogue_manager/components/code_edit_syntax_highlighter.gd, addons/dialogue_manager/constants.gd
This fixes the syntax highlighting for `import` and `using` lines.
=> Fix import & using syntax highlighting

addons/dialogue_manager/plugin.gd
Small QoL change to address the plugin unnecessarily modifying the current scene each time Godot is opened.
Godot updated their docs a few months ago to specify Autoloads should be added and removed in the `_enable_plugin` and `_disable_plugin` functions respectively.
https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html#registering-autoloads-singletons-in-plugins
The related PR/comment that addressed this: https://github.com/godotengine/godot/issues/68285#issuecomment-2362438548
=> Moving add and remove autoload to enable and disable plugin functions

addons/dialogue_manager/DialogueManager.cs
This should fix the issue with the ID not being set for DialogueLines in C#
see https://github.com/nathanhoad/godot_dialogue_manager/issues/818
=> Set Id in DialogueLine

addons/dialogue_manager/export_plugin.gd
This adds the missing `_get_name` hook for the new export plugin.
=> Add missing export plugin name

addons/dialogue_manager/dialogue_manager.gd
This changes how C# Task methods are found so that it actually checks the file extension of the state script.
Fixes #823
=> Improve the way C# methods are identified

addons/dialogue_manager/components/find_in_files.gd, addons/dialogue_manager/components/search_and_replace.gd
This fixes an issue where after replacing a find-and-replace result the results list would be reset.
Fixes #834
=> Fix find and replace index reset

addons/dialogue_manager/export_plugin.gd
This restores the internal translations file when exporting projects.
Fixes #835
=> Restore missing exported internal translations

addons/dialogue_manager/dialogue_manager.gd
This fixes an issue introduced in #827 when states didn't have a script to check.
=> Ensure state has script before checking script

addons/dialogue_manager/views/main_view.gd
Tiny change:
Now scrolls the clicked search result of "find in files" feature into view when opening the file.
adds feature described in #844
=> Find in files now centers on clicked search result

Dialogue Manager.csproj, addons/dialogue_manager/components/code_edit_syntax_highlighter.gd
This fixes the syntax highlighting for when a line has a line ID defined but no character.
Fixes #843
=> Fix line ID highlighting when there's no character

addons/dialogue_manager/dialogue_manager.gd
This is just a refactor of concurrent line handling to remove the need for `duplicate`.
=> Rework concurrent line fetching

addons/dialogue_manager/compiler/compilation.gd, addons/dialogue_manager/compiler/tree_line.gd, addons/dialogue_manager/constants.gd, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, addons/dialogue_manager/views/main_view.gd
This now flags nested dialogue lines that contain invalid things (eg. static line IDs, extra jumps, etc) as compile errors.
Fixes #852
=> Improve nested dialogue compile warnings

addons/dialogue_manager/import_plugin.gd
Previously, dialogue files that contained errors would be flagged in the importer as a parsing error. While technically correct the real world experience was that invalid dialogue files were then sometimes impossible to open in the dialogue editor until they were fixed externally.
This changes the dialogue importer to now let files that contain errors to pass the import process. Errors are still reported and if there are known files containing errors the game build step will still fail so any errors can be seen there.
Closes #863
=> Stop invalidating resources with errors

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/dialogue_manager.gd, tests/test_basic_dialogue.gd
This adds the methods `static_id_to_line_id` and `static_id_to_line_ids` for resolving static line IDs to actual line IDs. `static_id_to_line_id` will return the first line found that matches the static ID whereas `static_id_to_line_ids` will return an array of IDs (most often with a length of one but could be more as static line IDs can be used on more than one line if the text is identical).
=> Add methods for finding lines by their static IDs

addons/dialogue_manager/compiler/compilation.gd, tests/test_basic_dialogue.gd
This adds better errors for when nested/multiline dialogue isn't formatted correctly.
=> Better handle nested dialogue errors

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/components/code_edit.gd
This fixes an issue where a C# mutation was defined with optional parameters and then called without them.
=> Fix issue with optional C# mutation parameters

addons/dialogue_manager/components/code_edit.gd, addons/dialogue_manager/settings.gd, docs/Settings.md
This adds an advanced setting for providing extra sources for auto-complete in the dialogue editor.
The main use case is for when your dialogue balloon inserts itself into the `extra_game_states` at runtime. In that scenario, it is impossible for the dialogue editor to know about the balloon's members ahead of time so you can add it to the sources list in order to get some auto-complete options.
=> Add setting for extra auto-complete sources

addons/dialogue_manager/compiler/compilation.gd, addons/dialogue_manager/compiler/expression_parser.gd, addons/dialogue_manager/dialogue_manager.gd, tests/test_state.gd
This adds support for providing multiple values (separated by comma) per `when` clause to match against. For example:
```
match SomeGlobal.some_property
when 1, 3
It's one or three.
when 4, 5, 6
It's four, five, or six.
else
It's none of them.
```
=> Allow multiple values in when clauses

addons/dialogue_manager/views/main_view.gd
Fixes #879
1. Search should re-trigger when a file is selected in the file list
https://github.com/user-attachments/assets/88c2b7eb-5e7b-406c-9264-3a5703788f03
2. Search should re-trigger when a new file is opened
https://github.com/user-attachments/assets/6e629f08-53a1-45f9-a956-f0e3d35849a6
=> Fix search not updating on file change

addons/dialogue_manager/plugin.gd, addons/dialogue_manager/settings.gd
Previously, translations_pot_files would be updated on save to add new dialogue
files and remove deleted ones.
Some projects may prefer to manage this property manually. In particular,
because the property is serialised by Godot as a single line, parallel branches
which each add dialogue files are guaranteed to cause Git conflicts.
Add a setting to disable this behaviour. Default to the previous behaviour.
Fixes #887
=> Add setting to disable automatic adding of dialogue to POT file

addons/dialogue_manager/compiler/compilation.gd
This fixes a bug where expression jumps in imported dialogue were throwing an "invalid title" error.
Fixes #911
=> Fix snippet expression jumps

addons/dialogue_manager/dialogue_manager.gd
Previously, expressions that existed in translations needed the same expression to exist within the base translation. This change allows for expressions to be parsed at runtime for cases where the base dialogue text was empty. Under recommended usage, this shouldn't really ever happen but I'd rather handle the case gracefully than it just not working.
Closes #913
=> Allow translations in expressions without origin

addons/dialogue_manager/dialogue_manager.gd
This pushes the error message getting to only happen if there is an actual error to get a message for.
=> Fix runtime expression error checking

addons/dialogue_manager/dialogue_label.gd, docs/API.md, docs/Using_Dialogue.md
This adds a `started_typing` signal into the `DialogueLabel` class to mirror the `finished_typing` signal and help with making animations for character portraits easier without workarounds.
Docs have been updated to show the change in the API as well.
=> Add started_typing signal to DialogueLabel

addons/dialogue_manager/dialogue_label.gd
This adds better support for subclassing the `DialogueLabel` by exposing an `_update_text` method that is called when the `dialogue_line` property is set.
=> Allow overriding dialogue label text setter

addons/dialogue_manager/dialogue_manager.gd, tests/test_state.gd
Looks like there was some confusion in the compound conditional.
This fix applies to dialogue like this, for the example integer 2,
```
match SomeClass.AnIntegerEqualToTwo
when < 2
Bob: hello
when 2
Bob: hello again
```
=> Fix incorrectly failing match cases

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/dialogue_manager.gd
This adds a C# bridge to the getline function, copying most of the logic from the get_next_dialogue_line function.
Let me know if you'd like me to combine my PR's rather than do them separately.
=> Add GetLine to C#

addons/dialogue_manager/dialogue_label.gd
Recently, it was made possible to override how the text is set in the dialogue label so that you can modify it before display, so that you can add BBCodes and the like if you want. (#933) This failed to update the location where the text is *actually* set for typing out, meaning that the effects wouldn't be seen. This pull request makes the relevant location use `_update_text()` instead, updating the text appropriately.
=> Make dialogue label use _update_text() when setting text in type_out()

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/dialogue_manager.gd
The C# get_next_dialogue_line command was missing the MutationBehavior argument present in its gdscript counterpart. This PR adds it back in.
The bridge dislikes converting between the two langauages' enum types so I worked around it by stringifying them in the bridge. This solution does suffer from having to define MutationBehavior in both C# and gdscript, which could lead to issues if you add an extra value to one but not the other, but overall it does get the job done. Other suggestions and solutions are of course welcome.
=> Add MutationBehavior passthrough to C# get_next_dialogue_line bridge

addons/dialogue_manager/dialogue_responses_menu.gd
This adds a `response_focused` signal to the `DialogueResponsesMenu` node for detecting when the highlighted option changes.
=> Add a signal for when focused response changes

addons/dialogue_manager/dialogue_manager.gd, tests/test_basic_dialogue.gd
This fixes an issue where random line groups would stall if none passed their condition.
=> Skip random group if none pass their conditions

addons/dialogue_manager/views/main_view.gd
When Generating line IDs in the dialogue editor the view scrolls to the very top instead of staying at the current position.
This has been fixed by restoring scroll_vertical after generating the line IDs
_If this is a change to the compiler then make sure to add/update any tests that may be affected._
no change to compiler
_If this change needs updates to the documentation then make sure you've made those changes too._
no need to update docs
=> Stop dialogue editor scrolling to top when generating line IDs

tests/test_extracting_markers.gd
Found a regression in f216b65a93415eb44e62f827df64e3ef20a6f5de that breaks one of the project's testcases. (the pauses dictionary was removed)
This PR fixes the aforementioned test and adds a new one for the introduced case. Feel free to alter the introduced cases as you see fit, I figured i'd go ahead and over test rather than under test.
=> Fix broken test case

addons/dialogue_manager/components/code_edit.gd, addons/dialogue_manager/plugin.gd
This adds <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>b</kbd>/<kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>b</kbd> for inserting bold bbcode and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd>/<kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd> for inserting italic.
Closes #969
=> Add shortcuts for bold and italic bbcodes

addons/dialogue_manager/components/code_edit.gd, addons/dialogue_manager/dialogue_line.gd, addons/dialogue_manager/example_balloon/example_balloon.gd, addons/dialogue_manager/example_balloon/example_balloon.tscn, addons/dialogue_manager/example_balloon/small_example_balloon.tscn
This adds support for simple voice overs. When dragging an `AudioStream` file from the file system onto a line it will insert a `[#voice=<UID>]` tag that points to the audio file's UID. The example balloon will also now check for those tags and play them as voice lines, wait for them to finish, and then auto advance to the next line.
=> Add support for simple voice overs
