nathanhoad/godot_dialogue_manager

addons/dialogue_manager/views/main_view.gd
Many problems escaped my attention in my last push, so here's a PR to fix them.
It includes fixes for the following:
- New files not getting the config Godot requires to use the po file (didn't notice it because I was only testing adding strings to existing files)
- "?" being escaped, when msgfmt identifies that as an error
- "'" being escaped, when msgfmt identifies that as an error
- extra newline being added every time a po file is updated
=> Several fixes for PO saving

addons/dialogue_manager/inspector_plugin.gd
=> fix "property not found" error

addons/dialogue_manager/components/code_edit.gd, addons/dialogue_manager/views/main_view.gd, addons/dialogue_manager/views/main_view.tscn
-Templates-
1. Title Template
2. Dialogue Template
3. Responses Template
4. Random Lines Template
5. Random Text Template
-Actions-
1. Jump to Title
2. End Dialogue
=> Added Insert options as a QOL Features

README.md
I stumbled over the editor from your YouTube videos, but didn't have them running when making my first steps with the project. The written documentation is generally really good, but I was lost for ~30 minutes before figuring out that I shouldn't start the test scene via Godots "Play this Scene"-button, but the Dialogue specific button in the editor instead. For me this little hint in the README would've helped tremendously.
=> README.md: Hint about Editor UI & Test scene

addons/dialogue_manager/components/code_edit.gd, addons/dialogue_manager/components/parser.gd, docs/Writing_Dialogue.md
This pull request adds while loops to the language. 
The parser keeps track of "while" lines as it goes in `while_loopbacks` , finding the last line inside the while block, at the end changing its next-id style properties to point back to the beginning of the loop.
The code editor recognizes 'while' as a conditional keyword.
Documentation is updated.
- Standalone while loop
- While loop with nested if
- While loop with nested while
- While loop with nested if as the last line(s) in the block
- While loop with nested while as the last line(s) in the block
- While loop as the final lines of the script, or before an => END
- While loop as part of a response
- While loop with a goto as the last line in the block
- While loop with a snippet goto as the last line in the block
=> While loop

addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/components/resolved_line_data.gd, addons/dialogue_manager/dialogue_line.gd, addons/dialogue_manager/dialogue_manager.gd, docs/Writing_Dialogue.md
As for inline mutations, I've thought inline conditions could be a good thing to use.
I propose to add this with the following syntax:
```
Nathan: Something [if something_else]something else[/if]
```
=> Add inline conditions in dialogue line

addons/dialogue_manager/dialogue_manager.gd
This adds support for calling static properties and methods on classes.
Closes #214
=> Allow calling methods on classes

addons/dialogue_manager/dialogue_line.gd, addons/dialogue_manager/dialogue_resource.gd, addons/dialogue_manager/dialogue_response.gd
This adds some more documentation to the internal editor docs.
=> Add more code docs

addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/zh-cn.po
Added translate `zh-cn` in 5 commits.
Some key does not translated because I don't know where they used.
=> Added translate: zh-cn

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, docs/CSharp.md, examples/dialogue_for_csharp.dialogue, examples/dialogue_for_csharp.dialogue.import, examples/test_scenes/TestScene.cs, examples/test_scenes/csharp_scene.tscn, project.godot
This fixes being able to use mutations to request values (and modifies the C# example to ask for the players name in a C# native way).
=> Fix being able to await mutations in C#

addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/dialogue_manager.gd
Make non-functional changes that fix warnings raised by the Godot debugger.
=> Fix warnings

addons/dialogue_manager/l10n/zh-tw.po
Added Traditional Chinese
Fixed Simplified Chinese
Patched some new strings into Simplified Chinese
=> Added Traditional Chinese, fixed Simplified Chinese and patched updated strings

addons/dialogue_manager/components/search_and_replace.gd, addons/dialogue_manager/views/main_view.gd
This adds some improvements to the search and replace form.
Closes #256 
Closes #255
=> Improve search and replace

addons/dialogue_manager/components/parser.gd
Related to the issue described here: https://github.com/nathanhoad/godot_dialogue_manager/issues/270
=> Fix parser handling multiple layers of nested imports

addons/dialogue_manager/dialogue_label.gd, addons/dialogue_manager/example_balloon/example_balloon.gd, addons/dialogue_manager/plugin.gd, examples/point_n_click_balloon/balloon.gd, examples/portraits_balloon/balloon.gd, examples/visual_novel_balloon/balloon.gd
This adds `DialogueLabel` as a proper type so making custom balloons can be a bit more type safe.
Closes #271
=> Add DialogueLabel as a class name

addons/dialogue_manager/components/errors_panel.gd, addons/dialogue_manager/components/parser.gd
This fixes an issue when using indented newlines in an external file.
Fixes #281
=> Fix external indented lines

docs/Writing_Dialogue.md
Not sure if this is needed or even the right way to do this but I could not find any existing documentation for this.
=> Add Documentation for Escaping Characters

addons/dialogue_manager/l10n/en.po
hello! much love for this addon! Here's a quickie for a small typo I found in the error messages 🤠
=> Fix incomplete expression typo

addons/dialogue_manager/components/code_edit.gd
=> Fix crash on multiline commenting

addons/dialogue_manager/DialogueManager.cs, examples/test_scenes/TestScene.cs
This fixes C# `Task` mutations that have arguments.
=> Fix C# mutation arguments

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/dialogue_reponses_menu.gd, docs/CSharp.md, examples/csharp_balloon/Balloon.cs, examples/csharp_balloon/balloon.tscn, examples/csharp_balloon/small_balloon.tscn, examples/dialogue_for_csharp.dialogue, examples/test_scenes/TestScene.cs, examples/test_scenes/csharp_scene.tscn
This simplifies the C# example scene and balloon as well as expanding on how a developer would interact with properties between dialogue and C# classes.
This also adds the previously missing `Time` property from `DialogueLine`s.
=> Update C# usage docs and example

addons/dialogue_manager/components/code_edit_syntax_highlighter.gd, addons/dialogue_manager/plugin.gd
=> Fix leaked caches

addons/dialogue_manager/constants.gd, addons/dialogue_manager/l10n/zh.po, addons/dialogue_manager/l10n/zh_TW.po
constants.gd limited the string length of language code to 2 characters
but Chinese has Simplified(CN or SG) and Traditional(TW, HK or MO)
so i just removed the limit and added the 2-character language code to the fallback before English
patched new string
updated Traditional Chinese
=> Fixed and updated Chinese translations

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/example_balloon/example_balloon.gd, docs/API.md
This changes `show_example_dialogue_balloon` to return the example balloon.
=> Return example balloon from show method

addons/dialogue_manager/dialogue_manager.gd
This fixes an issue when inline mutations had their position adjusted (thanks to @Selenyhr)
=> Fix issue with adjusting inline mutations

addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/components/resolved_line_data.gd, addons/dialogue_manager/components/resolved_tag_data.gd, addons/dialogue_manager/dialogue_manager.gd
This adds more manually imported types to hopefully help C# stop forgetting class names.
=> Add workaround for C# forgetting more classes

addons/dialogue_manager/dialogue_label.gd
=> Fix auto pausing when typing out dialogue

addons/dialogue_manager/components/code_edit_syntax_highlighter.gd, addons/dialogue_manager/components/parse_result.gd, addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/constants.gd, addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/dialogue_resource.gd, addons/dialogue_manager/import_plugin.gd, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, docs/Writing_Dialogue.md, examples/dialogue.dialogue.import, examples/dialogue_for_csharp.dialogue.import, examples/dialogue_for_point_n_click.dialogue.import, examples/dialogue_for_visual_novel.dialogue.import, examples/dialogue_with_input.dialogue.import
This adds the `using` statement to declare state shortcuts in dialogue itself.
Closes #364
=> Add "using" statement

addons/dialogue_manager/dialogue_reponses_menu.gd
This allows the response template to share signals (other than pressed-related signals) with responses that are created from it.
Fixes #371
=> Hide response template instead of removing it

examples/portraits_balloon/balloon.gd, examples/visual_novel_balloon/balloon.gd
=> Fix incorrect references in examples

addons/dialogue_manager/components/dialogue_cache.gd, addons/dialogue_manager/import_plugin.gd, addons/dialogue_manager/plugin.gd, addons/dialogue_manager/views/main_view.gd
This moves the recompiling of dependent files into the import plugin (and re-arranges when/how dependencies are determined). This also introduces a (hopefully temporary) workaround for an issue in Godot 4.2 that crashes the editor when reimporting more than one resource at once.
Fixes #381
=> Change how dependendent files are recompiled

addons/dialogue_manager/components/dialogue_cache.gd, addons/dialogue_manager/components/settings.gd, addons/dialogue_manager/plugin.gd
This cleans up the POT file list when deleting dialogue files.
=> Tidy up POT file list when deleting dialogue files

.github/PULL_REQUEST_TEMPLATE.md, addons/dialogue_manager/components/parse_result.gd, addons/dialogue_manager/components/parser.gd, project.godot, tests/state_for_tests.gd, tests/test.gd, tests/test_basic_dialogue.gd, tests/test_extracting_markers.gd, tests/test_responses.gd, tests/test_state.gd, tests/tests.gd, tests/tests.tscn
This adds an initial test suite for the compiler. It is now the main scene for the project so to run the tests you can just run the project.
=> Add a test suite for the compiler

addons/dialogue_manager/components/parser.gd
This fixes an issue with importing when:
- A and B import C
- A imports B
=> Fix issue with shared imports

addons/dialogue_manager/components/files_list.gd, addons/dialogue_manager/views/main_view.gd, addons/dialogue_manager/views/main_view.tscn
I keep trying to close dialogue files with the middle mouse button because it works in the script editor.
=> Close files with middle mouse button

addons/dialogue_manager/components/parser.gd, tests/test_state.gd
=> Fix parse error with negative method arguments

addons/dialogue_manager/dialogue_manager.gd
This fixes an issue where using `ResourceLoader.load` would incorrectly be treated as if it was just the global `load`.
=> Fix mutations that use ResourceLoader.load()

addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/dialogue_reponses_menu.gd
This fixes an indexing issue when including responses that failed their condition checks.
=> Fix issue with disallowed responses index

addons/dialogue_manager/example_balloon/example_balloon.gd, addons/dialogue_manager/example_balloon/example_balloon.tscn
This makes the example balloon's click area cover the whole screen.
Fixes #456
=> Embiggen the clickable balloon area

addons/dialogue_manager/components/parse_result.gd, addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/dialogue_resource.gd, addons/dialogue_manager/import_plugin.gd
- the raw_text variable was added to the dialogue resource
- parser, parser_result and import_plugin were changed to import the new var
=> Add raw_text property to DialogueResource

addons/dialogue_manager/DialogueManager.cs, docs/CSharp.md
This adds `DialogueManager.ShowDialogueBalloon` to the C# API.
=> Add ShowDialogueBalloon to C# API

addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/dialogue_reponses_menu.gd, addons/dialogue_manager/example_balloon/ExampleBalloon.cs, addons/dialogue_manager/example_balloon/example_balloon.gd, addons/dialogue_manager/example_balloon/example_balloon.tscn, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, addons/dialogue_manager/plugin.gd, examples/csharp_balloon/Balloon.cs, project.godot
This updates the **Project > Tools > Create copy of dialogue example balloon...** tool to make a C# balloon if the project appears to be using C#.
=> Make Tool menu generate C# balloon if using C#

addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/example_balloon/example_balloon.tscn, addons/dialogue_manager/example_balloon/small_example_balloon.tscn, addons/dialogue_manager/plugin.gd, addons/dialogue_manager/settings.gd
This simplifies how/when a dotnet solution is detected in order to guess that the project is using C#.
=> Detect C# without having to run game first

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/dialogue_resource.gd, addons/dialogue_manager/plugin.gd, addons/dialogue_manager/settings.gd
This makes `DialogueResource` a `@tool` script so that it can be used live in the editor.
Closes #473
=> Make DialogueResource a tool script

addons/dialogue_manager/dialogue_manager.gd
=> Fix multiple different values for replacements

addons/dialogue_manager/components/update_button.gd, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, addons/dialogue_manager/settings.gd, addons/dialogue_manager/views/settings_view.gd, addons/dialogue_manager/views/settings_view.tscn
This adds an option to advanced settings to turn off auto-update.
=> Add option to turn off auto-update

addons/dialogue_manager/dialogue_manager.gd
This changes the line resolver to ignore response conditions because they would have already been resolved by that point.
Fixes #508
=> Stop double resolving response conditions

addons/dialogue_manager/dialogue_manager.gd
This defers the loading of autoloads and state shortcuts until they are first requested.
=> Defer loading game states until they are used

addons/dialogue_manager/dialogue_manager.gd
This adds special support for methods like `emit_signal` that are marked as `vararg`.
=> Add support for vararg methods like emit_signal

addons/dialogue_manager/components/code_edit_syntax_highlighter.gd, addons/dialogue_manager/components/parser.gd
This adds support for `&&` and `||` as operators.
=> Add support for C# logical operators

addons/dialogue_manager/l10n/uk.po
Made Ukrainian Translation for Dialogue Manager.
=> Add Ukrainian Translation

addons/dialogue_manager/components/dialogue_cache.gd, addons/dialogue_manager/components/update_button.gd, addons/dialogue_manager/import_plugin.gd, addons/dialogue_manager/plugin.gd, addons/dialogue_manager/views/main_view.gd
This adds support for detecting external file changes to update any open file buffers.
Closes #597
=> Reload files when modified externally

addons/dialogue_manager/components/parser.gd
This adds support for jump directives in regular dialogue lines.
Closes #599
=> Allow jumps at the end of regular dialogue lines

addons/dialogue_manager/views/main_view.gd
=> Fix cursor position resetting on save

addons/dialogue_manager/inspector_plugin.gd
=> Restore backwards compatibility with Godot 4.1

addons/dialogue_manager/components/code_edit.gd
=> Fix cursor position after delete line undo

addons/dialogue_manager/components/code_edit.gd, addons/dialogue_manager/components/code_edit_syntax_highlighter.gd, addons/dialogue_manager/components/dialogue_cache.gd, addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/dialogue_label.gd, addons/dialogue_manager/test_scene.gd
if this feels prescriptivist or too *erm, akshually*-ish, sorry.
the main things that have been done are:
- typo fixes
- grammatical inconsistency fixes (e.g.: in a function comment, „doing“ and „does“ are turned into „do“)
- non-sentence comment-ending period removals (often in comments that only contain a noun phrase)
=> Comment improvements

addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/l10n/en.po, docs/FAQ.md, docs/Writing_Dialogue.md, examples/dialogue_with_input.dialogue
This updated a few docs and error messages related to signals and state in general.
=> Update state/signal docs and error messages

addons/dialogue_manager/dialogue_manager.gd
=> Fix issue when responses came from a snippet

addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/plugin.gd, addons/dialogue_manager/views/main_view.gd, examples/dialogue_with_input.dialogue
=> Fix double returning from jump-and-returns

addons/dialogue_manager/components/code_edit.gd
=> Allow dropping any file into dialogue

addons/dialogue_manager/settings.gd, addons/dialogue_manager/views/main_view.gd, addons/dialogue_manager/views/settings_view.gd, addons/dialogue_manager/views/settings_view.tscn
This adds a setting for a custom new file template.
Closes #654
=> Allow custom new file template

addons/dialogue_manager/components/code_edit.gd
=> Add fallback to maintain Godot 4.1 compatibility

addons/dialogue_manager/components/code_edit_syntax_highlighter.gd, addons/dialogue_manager/components/parser.gd, addons/dialogue_manager/import_plugin.gd, examples/dialogue.dialogue.import, examples/dialogue_for_csharp.dialogue.import, examples/dialogue_for_point_n_click.dialogue.import, examples/dialogue_for_visual_novel.dialogue.import, examples/dialogue_with_input.dialogue.import
=> Fix responses passing through parent conditions

addons/dialogue_manager/components/code_edit.gd
=> Keep multiline selection after line move

addons/dialogue_manager/dialogue_manager.gd
=> Ignore type conversion of missing spread arguments

addons/dialogue_manager/components/parser.gd
=> Add support for non-english method names

addons/dialogue_manager/components/files_list.gd, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, addons/dialogue_manager/views/main_view.gd, addons/dialogue_manager/views/main_view.tscn
This adds an item to the "open" menu for quickly opening dialogue files.
=> Add "quick open"

addons/dialogue_manager/views/main_view.gd, addons/dialogue_manager/views/main_view.tscn
This sets a default file name when creating a new dialogue file.
=> Provide default file name

addons/dialogue_manager/components/code_edit.gd, addons/dialogue_manager/views/main_view.gd
This makes sure the titles list is up to date after an external file change.
=> Update titles list when file is externally changed

addons/dialogue_manager/example_balloon/example_balloon.gd, addons/dialogue_manager/utilities/builtins.gd
This adds support for `PackedStringArray` variables.
=> Add PackedStringArray builtin

addons/dialogue_manager/dialogue_label.gd
=> Fixes issue where multiple recursive goto lines don't reset the label text

addons/dialogue_manager/views/main_view.gd
=> Fix newlines breaking key generation

addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/example_balloon/ExampleBalloon.cs, addons/dialogue_manager/example_balloon/example_balloon.gd
=> Defer adding balloon to scene

addons/dialogue_manager/dialogue_manager.gd
=> Allow special quotes in translated replacements

addons/dialogue_manager/DialogueManager.cs, docs/CSharp.md
This push  mirrors GDScript's Create_Resource_From_String function into the c# wrapper and updates the c# documentation to reflect this.
=> Added CreateResourceFromString to the c# wrapper

addons/dialogue_manager/dialogue_reponses_menu.gd, addons/dialogue_manager/plugin.gd, addons/dialogue_manager/views/main_view.gd
=> Fix responses menu keyboard input

addons/dialogue_manager/compiler/compilation.gd, addons/dialogue_manager/compiler/resolved_goto_data.gd, addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/plugin.gd, tests/state_for_tests.gd, tests/test_jumps.gd
This stops an error when an import line is importing an empty string.
=> Fix importing when blank

docs/Basic_Dialogue.md
=> Restore [next] documentation

addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/utilities/builtins.gd, docs/Conditions_Mutations.md, tests/test_state.gd
This makes a new `self` property available to dialogue that points to the current `DialogueResource`.
=> Add "self" variable to refer to DialogueResource

addons/dialogue_manager/dialogue_manager.gd, tests/test_responses.gd
=> Fix issue when first nested line is a comment

addons/dialogue_manager/compiler/compilation.gd, addons/dialogue_manager/compiler/expression_parser.gd, addons/dialogue_manager/compiler/resolved_goto_data.gd, addons/dialogue_manager/compiler/resolved_line_data.gd, addons/dialogue_manager/components/code_edit_syntax_highlighter.gd, addons/dialogue_manager/dialogue_manager.gd
This improves the dialogue editor syntax highlighting.
Fixes #774
=> Improve syntax highlighting

addons/dialogue_manager/compiler/compilation.gd, addons/dialogue_manager/compiler/compiler_regex.gd, tests/test_basic_dialogue.gd
This fixes an issue where short titles were incorrectly flagged as errors.
Fixes #781
=> Fix incorrect error with short titles

addons/dialogue_manager/dialogue_manager.gd
This fixes an issue when building/checking the internal method info cache for methods with optional arguments.
=> Fix issue with optional args in method info cache

addons/dialogue_manager/DialogueManager.cs
This brings support for concurrent lines to C#.
=> Add concurrent lines to C#

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/dialogue_manager.gd
=> Fix AmbiguousMatchException for C# mutations

addons/dialogue_manager/components/code_edit_syntax_highlighter.gd
This adds a subtle highlight to character names.
=> Subtly highlight character names

Dialogue Manager.csproj, addons/dialogue_manager/export_plugin.gd, addons/dialogue_manager/export_plugin.gd.uid, addons/dialogue_manager/plugin.gd
This trims out any editor specific stuff from exported game builds.
=> Trim dialogue editor from exported builds

addons/dialogue_manager/components/code_edit.gd, addons/dialogue_manager/components/files_list.gd, addons/dialogue_manager/components/files_list.tscn, addons/dialogue_manager/components/title_list.gd, addons/dialogue_manager/l10n/en.po, addons/dialogue_manager/l10n/translations.pot, addons/dialogue_manager/test_scene.gd, addons/dialogue_manager/views/main_view.gd
This tweaks a few aspects of how the dialogue editor theming works.
=> Improve dialogue editor theming

docs/2to3.md
=> Fix Typo in 2to3.md

addons/dialogue_manager/compiler/compilation.gd, addons/dialogue_manager/components/code_edit_syntax_highlighter.gd
=> Fix imported titles that are indented

addons/dialogue_manager/settings.gd, addons/dialogue_manager/views/main_view.gd
This makes the dialogue editor remember your scroll position.
Closes #832
=> Remember scroll position for edited files

addons/dialogue_manager/dialogue_manager.gd
This fixes an issue where expression jumps would only evaluate the first time they were encountered, caching the result. Now, they will evaluate each time they are checked.
Fixes #836
=> Fix expression jumps only evaluating once

addons/dialogue_manager/compiler/compilation.gd
=> Fix setting for missing translation warning

addons/dialogue_manager/components/code_edit_syntax_highlighter.gd
=> Fix highlighting when no character but yes ID

addons/dialogue_manager/compiler/expression_parser.gd, addons/dialogue_manager/components/code_edit_syntax_highlighter.gd
=> Fix inline comment syntax highlighting

addons/dialogue_manager/compiler/compilation.gd
=> Fix responses if children of condition

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/compiler/compilation.gd, addons/dialogue_manager/compiler/expression_parser.gd, addons/dialogue_manager/components/code_edit.gd, addons/dialogue_manager/components/code_edit_syntax_highlighter.gd, addons/dialogue_manager/dialogue_manager.gd
This adds some basic auto completion for known state in mutation lines.
At this stage it only completes autoloads and one level deep properties/methods/signals and only on mutation lines (ie. not inline mutations).
=> Add basic auto complete for mutation lines

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/compiler/compilation.gd, addons/dialogue_manager/compiler/compiled_line.gd, addons/dialogue_manager/compiler/expression_parser.gd, addons/dialogue_manager/dialogue_manager.gd, addons/dialogue_manager/dialogue_response.gd, tests/test_responses.gd
This adds a `condition_as_text` property to `DialogueResponse`s to see what the original condition was for the response.
Related to #870
=> Add condition_as_text to DialogueResponses

docs/API.md
This just updates a couple of things in the API docs that were old.
=> Update API docs

addons/dialogue_manager/DialogueManager.cs, addons/dialogue_manager/components/code_edit.gd
This adds support for auto-complete to condition lines, using clauses, etc and also adds constants to the auto-complete list.
=> Add wider support for basic auto-complete

addons/dialogue_manager/plugin.gd, project.godot
This adds an extra reimport check pre-build to make sure changes have been compiled beforehand.
=> Ensure changes have been compiled before build

addons/dialogue_manager/views/main_view.gd
This is a stopgap fix until Godot 4.5 is released with [this native fix](https://github.com/godotengine/godot/pull/105277).
Fixes #884
=> Fix custom test scene failing to run from UID

addons/dialogue_manager/dialogue_responses_menu.gd
This adds left and right arrow navigation to the `DialogueResponsesMenu`.
=> Add left and right response menu navigation

addons/dialogue_manager/utilities/dialogue_cache.gd
=> Clear reimport list after reimporting

tests/CSharpState.cs, tests/test_state.gd
This just adds a test for using async state with C#.
=> Add a test for C# state

addons/dialogue_manager/example_balloon/example_balloon.tscn, addons/dialogue_manager/example_balloon/small_example_balloon.tscn
This simplifies the node structure of the example balloon to make it slightly easier to modify.
=> Simplify the example balloon node structure

addons/dialogue_manager/components/code_edit.gd
=> Fix do! autocomplete

docs/Conditions_Mutations.md
Integrates docs feedback in #901
=> Update Extra game state docs

addons/dialogue_manager/dialogue_manager.gd
This fixes #960 in a way that keeps compatibility with #499.
=> Ensure "dialogue_ended" doesn't emit too early

Dialogue Manager.csproj, addons/dialogue_manager/dialogue_manager.gd, project.godot
=> Adds some extra array types when checking values

addons/dialogue_manager/dialogue_manager.gd, tests/some_class.gd, tests/some_class.gd.uid, tests/test_state.gd
=> Fix class references
